apiVersion: v1
kind: Service
metadata:
  name: kp-service
spec:
  selector:
    app: kp
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8083
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kp
spec:
  selector:
    matchLabels:
      app: kp
  replicas: 4
  template:
    metadata:
      labels:
        app: kp
    spec:
      containers:
      - name: kp
        image: bharadwaj12/kuberp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083